services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP for Browser UI
      - "7687:7687" # Bolt for Programmatic Access
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_memory_heap_max__size=4G # Limits DB memory usage
      - NEO4J_dbms_memory_pagecache_size=2G
